server:
  port: 9000

#配置Eureka,制定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

#服务器名称
spring:
  application:
    name: api-gateway

zuul:
  routes:
    articleService: /api/huyun/**